# Generated by Django 5.1 on 2024-08-27 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0003_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_at',)},
        ),
    ]
