# Generated by Django 5.1 on 2024-08-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0006_remove_post_posts_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft')], default='active', max_length=10),
        ),
    ]
