# Generated by Django 5.1 on 2024-08-29 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0008_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
