# Generated by Django 5.1 on 2024-08-29 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0011_vent_ventcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vent',
            old_name='author_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='vent',
            old_name='author_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='vent',
            name='approved',
        ),
    ]
