# Generated by Django 5.1 on 2024-08-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0012_rename_author_email_vent_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vent',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
