# Generated by Django 5.1 on 2024-08-29 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0013_vent_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vent',
            old_name='email',
            new_name='author_email',
        ),
        migrations.RenameField(
            model_name='vent',
            old_name='name',
            new_name='author_name',
        ),
    ]
