# Generated by Django 5.1 on 2024-08-29 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0016_resources_remove_resourceitem_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('who_to_contact', 'Who to Contact'), ('where_to_go', 'Where to Go'), ('what_to_do', 'What to Do'), ('educational_resources', 'Educational Resources')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vlog.resourcecategory')),
            ],
        ),
        migrations.DeleteModel(
            name='Resources',
        ),
    ]
