# Generated by Django 5.1 on 2024-08-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0018_resources_remove_resourceitem_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='link',
        ),
        migrations.AddField(
            model_name='resources',
            name='intro',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
