# Generated by Django 5.1 on 2024-08-29 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0019_remove_resources_link_resources_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='content',
        ),
        migrations.AddField(
            model_name='resources',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ResourcesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resources', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vlog.resources')),
            ],
        ),
    ]
