# Generated by Django 5.1 on 2024-08-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0021_remove_resources_slug_resources_resource_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='resource_slug',
        ),
        migrations.AddField(
            model_name='resources',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ResourceItem',
        ),
    ]
