# Generated by Django 5.1 on 2024-08-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0022_remove_resources_resource_slug_resources_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Resources',
        ),
    ]
